spring:
  application:
    name: gateway
  security:
    require-ssl: true
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterAccess=1m,maximumSize=1000

server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: gateway
  http2:
    enabled: true

# Resilience4j Rate Limiter
resilience4j:
  ratelimiter:
    instances:
      gatewayRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1m
        timeoutDuration: 0s
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

# JWT Secret (Base64 randomico - 32 bytes)
jwt:
  secret: ${JWT_SECRET:sLkANuT7hSjTMuT1gpPUAoeJ60aGziD9yI00bJpWgxY=}  # Base64 de 32 bytes
  issuer: gateway-api

backend:
  url: http://localhost:8081

# Logging
logging:
  level:
    com:
      projeto_gateway:
        gateway: DEBUG
    org:
      springframework:
        security: INFO

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true